package:
  name: jieba-fast
  version: "0.52"

source:
  git_url: https://github.com/deepcs233/jieba_fast.git
  git_rev: 5e6b21dece184e1004a35bfd802c8772059de3ab

requirements:
  build:
    - pybind11 2.10.0
  host:
    - python