FROM androidsdk/android-31 

# 设置非交互模式，避免 apt 提示
ENV DEBIAN_FRONTEND=noninteractive

# 更新包列表并添加 deadsnakes PPA
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

# 更新包列表并安装软件包
RUN apt-get update && \
    apt-get install -y \
    git \
    vim \
    patch \
    patchelf \
    wget \
    unzip \
    openjdk-17-jdk \
    build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  # 清理缓存

RUN git clone https://github.com/chaquo/chaquopy.git /app/chaquopy &&\
    cd /app/chaquopy &&\
    git checkout 1ccebbe58016a9cad2d31e565464b36c19495337

# 下载并安装 Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_25.5.1-0-Linux-x86_64.sh && \
    bash Miniconda3-py310_25.5.1-0-Linux-x86_64.sh -b -p /opt/miniconda3 && \
    rm Miniconda3-py310_25.5.1-0-Linux-x86_64.sh

# 初始化并创建环境
ENV PATH="/opt/miniconda3/bin:$PATH"

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
RUN conda init bash && \
    /opt/miniconda3/bin/conda create -n py310 python=3.10 -y

# 默认激活
RUN echo 'conda activate py310' >> ~/.bashrc



SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "source /opt/miniconda3/etc/profile.d/conda.sh && \
    conda activate py310 && \
    python --version && \
    pip install --upgrade pip setuptools wheel && \
    pip install -r /app/chaquopy/server/pypi/requirements.txt &&\
    pip install numpy==1.25.0 &&\
    pip install setuptools_scm==8.1.0 &&\
    pip install cmake==3.29.2 &&\
    cd /app/chaquopy && \
    ./target/download-target.sh maven/com/chaquo/python/target/3.10.6-1"

SHELL ["/bin/bash", "-c"]
RUN /bin/bash -c "yes | sdkmanager --licenses && \
    yes | sdkmanager --install 'ndk;27.3.13750724'"

ENV ANDROID_NDK="/opt/android-sdk-linux/ndk/27.3.13750724"

# Install Rust and Cargo via rustup (non-interactive)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add Rust's bin directory to PATH (for cargo and rustc)
ENV PATH="/root/.cargo/bin:${PATH}"

# (Optional) Verify installation
RUN cargo --version && rustc --version

RUN rustup target add aarch64-linux-android

RUN rustup target list --installed

ENV PATH="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"

ENV GSV_ANDROID_BUILD=1

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN wget -q -O /tmp/mecab-0.996-ko-0.9.2.tar.gz https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz && \
    cd /tmp && \
    tar zxvf /tmp/mecab-0.996-ko-0.9.2.tar.gz && \
    cd mecab-0.996-ko-0.9.2 && \
    wget -q -O config.sub 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' && \
    wget -q -O config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' && \
    chmod +x config.sub config.guess

# 设置工作目录
WORKDIR /app

# 默认命令：启动构建，需要将项目挂载在/app/pyopenjtalk目录下
CMD ["/bin/bash"]